### ISSUE TITLE
Returning invalid url 

### ISSUE THREAD

**Issue by Prashast09** [TakuSemba/SampleDrmExoPlayer#1]
The hostname is null. I'm getting this null/drm/hls2/master.m3u8.Please let me know how to fix this

**Comment by TakuSemba** [comment]
you have to set domain name in local.properties.
It means you have to prepare your own valid url.

https://github.com/TakuSemba/SampleDrmExoPlayer/blob/master/app/build.gradle#L23

**Comment by Prashast09** [comment]
Can you please help on how to create a url and using it in local.properties

**Comment by TakuSemba** [comment]
https://medium.com/@takusemba/play-your-own-drm-content-on-exoplayer-e8ed73d5864c

**Comment by Prashast09** [comment]
It doesn't contains information about setting up Widevine License server.

**Comment by TakuSemba** [comment]
you can use the test server that google prepared for you.

**Comment by Prashast09** [comment]
It's returning  this err,
Packaging Error: 3 (INVALID_ARGUMENT): A decryption key source is not provided for an encrypted stream.

**Comment by TakuSemba** [comment]
This repo is just an sample app of showing how you can play given DRM contents with ExoPlayer. 

The error seems like you packaged the video wrong, and I think preparing DRM contents is out of this repo's scope.
